version: '3.5'

services:
  db:
    image: mysql:8.0-oracle
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: s3cret
      MYSQL_DATABASE: expenses
      MYSQL_USER: expenses
      MYSQL_PASSWORD: passwordexpenses
    volumes:
      - ./db:/var/lib/mysql

  server:
    image: pedroalv3s/spring-boot-expenses-demo
    restart: "on-failure"
    environment:
      DB_URL: jdbc:mysql://db:3306/expenses?connectTimeout=0&socketTimeout=0&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USERNAME: expenses
      DB_PASSWORD: passwordexpenses
#      SERVER_SERVLET_CONTEXT_PATH: /expenses
    ports:
      - "8094:8080"
    links:
      - db